spring.application.name=usuarios-service
server.port=8081

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.instance-id=${spring.application.name}:${random.value}
eureka.instance.lease-renewal-interval-in-seconds=5
eureka.instance.lease-expiration-duration-in-seconds=10

# --- CONFIGURACIÓN DEL CIRCUIT BREAKER ---
# Tamaño de la ventana: evaluará las últimas 5 peticiones
resilience4j.circuitbreaker.instances.datosServiceCB.slidingWindowSize=5
# Porcentaje de fallo para abrir el circuito (50% = si 3 de 5 fallan, se abre)
resilience4j.circuitbreaker.instances.datosServiceCB.failureRateThreshold=50
# Tiempo que esperará en estado abierto antes de intentar probar de nuevo (estado half-open)
resilience4j.circuitbreaker.instances.datosServiceCB.waitDurationInOpenState=10s
# Cuántas peticiones dejará pasar en estado half-open para probar si el servicio se recuperó
resilience4j.circuitbreaker.instances.datosServiceCB.permittedNumberOfCallsInHalfOpenState=2